### ISSUE TITLE
About the adjoint scaling factor

### ISSUE THREAD

**Issue by WangLicheng-HIT** [drh0111/lumopt_drh#1]
Now I want to use lumopt to define my own fom but the gradient is always not correct because I can not sure the adjoint source has been setted right or not. And I find a tricky parameter here : 
`def get_adjoint_field_scaling(self, sim):
        omega = 2.0 * np.pi * sp.constants.speed_of_light / self.wavelengths
        adjoint_source_power = ModeMatch.get_source_power(sim, self.wavelengths)
        scaling_factor = np.conj(self.phase_prefactors) * omega * 1j / np.sqrt(adjoint_source_power)
return scaling_factor`

Do you know the meaning of this parameter scaling _factor?
Thanks

**Comment by drh0111** [comment]
You can refer to the paper "_Adjoint shape optimization applied to electromagnetic design_" **Optics Express** (2013) for the origin of this scaling factor.
